const handleException = function (error) {
  console.log(error);
};

export { handleException };
